language: ruby
cache: bundler
rvm:
  - 2.0.0
before_script: "bundle exec license_finder"
after_success:
  - echo "+++ 1) License Finder Completed successfully +++"
after_failure:
  - echo "--- 1) License Finder Failed ---"
script: "bundle exec rspec"
after_success:
  - echo "+++ TESTS Passed +++"
after_failure:
  - echo "--- TESTS Failed ---"
notifications:
  email:
    recipients:
    - matthew.larson@flukenetworks.com