language: ruby
rvm:
  - 2.0.0
script: ./license_test.sh
after_success:
  - echo "--- All Licenses have been approved. ---"
after_failure:
  - echo "--- License finder found un-approved licenses. ---"
notifications:
  email:
    recipients:
    - matthew.larson@flukenetworks.com