language: ruby
cache: bundler
rvm:
  - 2.0.0
script: "bundle exec license_finder"
after_success:
  - echo "+++ License Finder Completed successfully +++"
after_failure:
  - echo "--- License Finder Failed ---" $TRAVIS_TEST_RESULT
notifications:
  email:
    recipients:
    - matthew.larson@flukenetworks.com