language: ruby
cache: bundler
rvm:
  - 2.0.0
before_script:
  - echo "--- About to run license_finder. ---"
  - echo "Current Directory: " $PWD
  - license_finder
  - echo "--- license_finder finished. ---"
notifications:
  email:
    recipients:
    - matthew.larson@flukenetworks.com