language: ruby
rvm:
  - 2.0.0
after_success:
  - echo "--- About to run license_finder. ---"
  - license_finder
  - echo "--- license_finder finished. ---"
notifications:
  email:
    recipients:
    - matthew.larson@flukenetworks.com