---
whitelist:
- MIT
- Apache 2.0
- ruby
- other
- LICENSE
- BSD
- Perl Artistic v2
- GNU GPL v2
ignore_groups:
#- test
#- development
ignore_dependencies:
 - diff-lcs
 - mime-types
 - pg
 - ox
#- bundler
dependencies_file_dir: './doc/'
project_name: to_do_app
gradle_command: # only meaningful if used with a Java/gradle project. Defaults to "gradle".
